AUT-1487: WIP
alphagov/di-authentication-api pull request #3194
Opened 2023-08-01 11:24 UTC by ayoshebby

WIP

2023-08-02 08:06 UTC, JHjava reviewed
Looks good. Few minor comments

2023-08-02 08:06 UTC, JHjava commented on shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoAuthCodeService.java
> +        update(authCode);
I reckon we won't need these methods. We will only ever create an auth code, update the has been used or read the auth code store

2023-08-02 08:06 UTC, JHjava commented on shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
> +    public boolean isAuthCodeStoreEnabled() {
Can't see this used anywhere. Do we use this in the DynamoAuthCodeService?

2023-08-02 10:51 UTC, two-first-names requested changes

2023-08-02 10:51 UTC, two-first-names commented on ci/terraform/shared/dynamodb.tf
> +    enabled = !var.use_localstack
enabled = true

2023-08-02 10:51 UTC, two-first-names commented on ci/terraform/shared/dynamodb.tf
> +    enabled = !var.use_localstack
enabled = true

2023-08-03 08:58 UTC, two-first-names requested changes

2023-08-03 08:58 UTC, two-first-names commented on ci/terraform/shared/kms.tf
> +  count = var.use_localstack ? 0 : 1
No need for count = anymore, localstack isn't ever going to be used and it complicates things.

2023-08-03 09:02 UTC, two-first-names approved these changes

2023-08-03 12:40 UTC, merged