Lambda handler for removing an account
alphagov/di-authentication-api pull request #438
Opened 2021-09-06 12:49 UTC by cj1993

## What?

New handler for for removing an account (user profile + user credentials)

## Why?

Users want to be able to remove their account.

2021-09-06 13:07 UTC, dbes-gds commented on account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandler.java
> +            SessionService sessionService) {
couple of unused params

2021-09-06 13:08 UTC, dbes-gds commented on account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandler.java
> +        try {
add some logging to help with debuggin?

2021-09-06 13:32 UTC, sanisc requested changes

2021-09-06 13:32 UTC, sanisc commented on account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandler.java
> +                    objectMapper.readValue(input.getBody(), RemoveAccountRequest.class);
you want to read the principal id from the request and do some basic validation to make sure the users subjects match up

2021-09-06 15:40 UTC, JHjava submitted a review, later dismissed

2021-09-07 08:00 UTC, sanisc requested changes

2021-09-07 08:00 UTC, sanisc commented on ci/terraform/account-management/remove-account.tf
> +  endpoint_name   = "remove-account"
can we change this to delete-account

2021-09-07 08:31 UTC, sanisc approved these changes

2021-09-07 08:32 UTC, merged